# database
DATABASE_NAME = 'ChatbotData'
TRANSACTION_SIZE = 1000

# dataset
MINIMUM_ACCEPTED_SCORE = 2
BUFFER_SIZE = 1000
MAXIMUM_NUMBER_OF_WORDS = 50
MAXIMUM_NUMBER_OF_CHARS = 800
NEW_LINE = ' new_line '

# chatbot
RETRIEVAL_SIZE = 10000